manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/yiancar
    - name: sekigon-gonnoc
      url-base: https://github.com/sekigon-gonnoc
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: ad99557d3311f927d3a45a8dc935c880645e17f1
      import: app/west.yml
    - name: zmk-feature-status-led
      remote: sekigon-gonnoc
      revision: main
  self:
    path: config
