manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/yiancar
    - name: sekigon-gonnoc
      url-base: https://github.com/sekigon-gonnoc
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 8a26c29a1c6f77fb216f85b202df15c5585108e3
      import: app/west.yml
    - name: zmk-feature-status-led
      remote: sekigon-gonnoc
      revision: main
  self:
    path: config
